name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          filename: github-metrics.svg
          config: |
            template: classic
            base: header, activity, community, repositories, metadata

            plugins:
              - isocalendar
              - languages
              - leetcode

            # IsoCalendar
            isocalendar:
              enabled: true
              duration: full-year

            # Most used languages
            languages:
              enabled: true
              details: bytes-size, percentage
              threshold: 1%
              hide:
                - html
                - css

            # LeetCode
            leetcode:
              enabled: true
              user: LucNIK
              sections: solved, skills, recent
