name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          # Base
          base: header, activity, community, repositories, metadata

          # Template
          template: classic

          # --------------------------
          # ðŸ“Œ Plugins activÃ©s
          # --------------------------

          # IsoCalendar full year
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Languages
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 1%
          plugin_languages_ignored: html, css

          # LeetCode
          plugin_leetcode: yes
          plugin_leetcode_user: LucNIK
          plugin_leetcode_sections: solved, skills, recent
