name: GitHub Snake

on:
  schedule:
    - cron: '0 0 * * *' # Exécution quotidienne à minuit UTC
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: LucNIK
          outputs: |
            # Mode clair (jour)
            dist/github-snake-light.svg?color_snake=#F3BA2F&color_dots=#eeeeee,#dddddd,#cccccc,#bbbbbb,#aaaaaa&color_background=#ffffff
            # Mode sombre (nuit)
            dist/github-snake-dark.svg?color_snake=#800020&color_dots=#aa0011,#990011,#880011,#770011,#660011&color_background=#ffffff

      - name: Commit updated Snake
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add dist/*
          git commit -m "Update GitHub Snake" || echo "No changes to commit"
          git push
