name: GitHub Snake

on:
  schedule:
    # Exécute tous les jours à 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: LucNIK
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9&color_background=#aaaaaa

      - name: Commit Snake
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add dist/*
          git commit -m "Update GitHub Snake" || echo "No changes to commit"
          git push
