name: GitHub Snake GIF Colorized

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Snake jaune Binance (jour), cases gris par défaut
      - name: Generate GitHub Snake GIF (day)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake-day.gif?color_snake=%23F3BA2F&color_background=%23FFFFFF

      # Snake rouge bordeaux (nuit), cases gris foncé par défaut
      - name: Generate GitHub Snake GIF (night)
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake-night.gif?color_snake=%23800020&color_background=%23000000

      # Commit automatique
      - name: Commit generated GIFs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add colorized GitHub Snake GIFs"
          branch: main
          file_pattern: dist/
